services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data
    restart: on-failure

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  api:
    build: .
    container_name: api
    command: >
      bash -c "./wait-for-it.sh postgres:5432 -- python manage.py migrate && daphne -b 0.0.0.0 -p 8000 FreskitoBCN.asgi:application"
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "8080:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    restart: on-failure
